<html lang="es">

    <head>
        <meta charset="UTF-8">
        <title>Revisiones</title>
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    </head>

    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">Inicio</a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/admin/nueva-categoria">Crear Categoria</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/empresa/crear-publicacion">Crear Publicación</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/admin/categorias">Categorias</a>
            </li>
            <!--<li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/empresa/registro">Como Empresa</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/registro">Registro</a>
            </li>
            -->
          </ul>
        </div>
      

    <div class="col-md-6 text-end">
        <ul class="nav">
            <li class="nav-item"><a href="/login" class="nav-link link-dark px-2">Login</a></li>
            <li class="nav-item"><a href="/registro" class="nav-link link-dark px-2">Registro</a></li>
            <li class="nav-item"><a href="/empresa/registro" class="nav-link link-dark px-2">Registro Empresa</a></li>

        </ul>
    </div>


      </div>
    </nav>