<html lang="es">

    <head>
        <meta charset="UTF-8">
        <title>Revisiones</title>
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    </head>

    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">Inicio</a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/nueva-categoria">Crear Categoria</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/crear-anuncio">Crear Anuncio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/categorias">Categorias</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/registro-empresa">Empresa</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>